[package]
name = "florestad"
version = "0.8.0"
edition = "2021"
license = "MIT"
description = """
The main binary for Floresta, a lightweight Bitcoin node implementation in Rust,
utilizing Utreexo for efficient state management.

This binary is a cli utility to run the full node, and interact with it via RPC. You may also
run this binary as a daemon on unix systems. There's a couple of features and command-line
options to customize the node to your needs. Check out the README.md and the documentation
for more information on how to use and configure Florestad.
"""
repository = "https://github.com/vinteumorg/Floresta"
readme.workspace = true # Floresta/README.md
keywords = ["bitcoin", "utreexo", "node", "blockchain", "rust"]
categories = ["cryptography::cryptocurrencies", "command-line-utilities"]

[dependencies]
bitcoin = { workspace = true }
clap = { workspace = true }
console-subscriber = { workspace = true, optional = true }
dirs = "4.0"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["chrono", "ansi", "env-filter"] }

# Local dependencies
floresta-node = { workspace = true }

[target.'cfg(unix)'.dependencies]
daemonize = { version = "0.5.0" }

[build-dependencies]
toml = { workspace = true }

[features]
default = ["json-rpc"]
compact-filters = ["floresta-node/compact-filters"]
zmq-server = ["floresta-node/zmq-server"]
json-rpc = ["floresta-node/json-rpc", "compact-filters"]
metrics = ["floresta-node/metrics"]
tokio-console = ["dep:console-subscriber"]

[lints]
workspace = true
