[package]
name = "utreexo-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
rustreexo = { git = "https://www.github.com/mit-dci/rustreexo" }
btcd-rpc = { git = "https://github.com/Davidson-Souza/rust-btcd-rpc", features = ["utreexod"], branch = "use-reqwest"}
clap = {version = "4.0.29", features = ["derive"]}
sha2 = "^0.10.6"
async-std = "1.12.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kv = "0.24.0"
bitcoin = {version = "0.29", features = ["serde", "std", "bitcoinconsensus"]}
miniscript = "9.0.0"
pretty_env_logger = "0.4.0"
futures = "0.3.4"
rmp-serde = "1.1.1"
toml = "0.5.10"
argfile = "0.1.5"
dirs = "4.0.0"
signal-hook = "0.3.14"

[dev-dependencies]
# for random filenames in tests
rand = "0.8.5"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
