[workspace]
resolver = "2"
members = [
    "florestad",
    "crates/floresta",
    "crates/floresta-errors",
    "crates/floresta-chain",
    "crates/floresta-cli",
    "crates/floresta-common",
    "crates/floresta-compact-filters",
    "crates/floresta-electrum",
    "crates/floresta-watch-only",
    "crates/floresta-wire",
]

[patch."https://github.com/rust-lang/crates.io-index"]

# we use a fork of the bitcoin crate, which is not published on crates.io
# because it doesn't have utreexo support (yet?)
bitcoin = { git = "https://github.com/Davidson-Souza/rust-bitcoin", rev = "eb5d7a3896fff0ebf6394dabc882d46e439695be" }
