[package]
name = "floresta"
version = "0.3.0"
edition = "2021"

[dependencies]
rustreexo = { git = "https://www.github.com/mit-dci/rustreexo" }
btcd-rpc = { git = "https://github.com/Davidson-Souza/rust-btcd-rpc", features = ["utreexod"], branch = "use-reqwest", optional = true }
clap = { version = "4.0.29", features = ["derive"] }
sha2 = "^0.10.6"
async-std = { version = "1.12.0", features = ["attributes"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kv = "0.24.0"
# Using master branch of miniscript because the multipath feature for output descriptor parsing isn't released yet
miniscript = { git = "https://github.com/douglaz/rust-miniscript.git", branch = "master-2023-03-30" }
pretty_env_logger = "0.4.0"
futures = "0.3.4"
rmp-serde = { optional = true, version = "1.1.1" }
toml = "0.5.10"
argfile = "0.1.5"
dirs = "4.0.0"
signal-hook = "0.3.14"
rand = "0.8.5"
bitcoin = { version = "0.29", features = ["serde", "std", "bitcoinconsensus"] }
slip132 = "0.9.0"
dns-lookup = "1.0.8"

[dev-dependencies]
pretty_assertions = "1"

[features]
default = ["experimental-p2p"]
cli-blockchain = ["rmp-serde", "btcd-rpc"]
experimental-p2p = []

[patch."https://github.com/rust-lang/crates.io-index"]
bitcoin = { git = "https://github.com/Davidson-Souza/rust-bitcoin", rev = "a320c6535567acd3771da37759a7644eea5c6eb2" }
