[workspace]
resolver = "2"
members = [
    "florestad",
    "fuzz",
    "metrics",
    "crates/floresta",
    "crates/floresta-chain",
    "crates/floresta-cli",
    "crates/floresta-common",
    "crates/floresta-compact-filters",
    "crates/floresta-electrum",
    "crates/floresta-watch-only",
    "crates/floresta-wire",
]

default-members = [
    "florestad",
    "crates/floresta",
    "crates/floresta-chain",
    "crates/floresta-cli",
    "crates/floresta-common",
    "crates/floresta-compact-filters",
    "crates/floresta-electrum",
    "crates/floresta-watch-only",
    "crates/floresta-wire",
]
