[package]
name = "floresta-electrum"
version = "0.2.0"
edition = "2021"
authors = ["Davidson Souza <davidson.lucas.souza@outlook.com>"]
description = """
    A simple Electrum server implementation for Floresta. It is based on the
    Electrum protocol specification and works out of the box with any wallet
    that supports Electrum servers.
"""
repository = "https://github.com/vinteumorg/Floresta"
license = "MIT"
readme = "README.md"
keywords = ["bitcoin", "utreexo", "node", "blockchain", "rust"]
categories = ["cryptography::cryptocurrencies"]

[dependencies]
floresta-common = { path = "../floresta-common" }
floresta-chain = { path = "../floresta-chain" }
floresta-watch-only = { path = "../floresta-watch-only" }
floresta-compact-filters = { path = "../floresta-compact-filters" }
floresta-wire = { path = "../floresta-wire" }

rustreexo = "0.3.0"
sha2 = "^0.10.6"
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.22"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kv = "0.24.0"
miniscript = "12"
futures = "0.3.4"
toml = "0.5.10"
bitcoin = { version = "0.32", features = ["serde", "std", "bitcoinconsensus"] }
thiserror = "1.0"
core2 = { version = "0.4.0", default-features = false }

[dev-dependencies]
rand = "0.8.5"
rcgen = "0.13"
zstd = "0.13.2"
